<a href="https://colab.research.google.com/github/ashika69/ML-Basics/blob/main/NumpyDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy**

A python library which supports high-dimensional array and mathematical operations and functions to be performed on the array.

In [ ]:
import numpy as np

Creation of an array using numpy

In [ ]:
np.arange(1,11)  #arange method is used same as the range.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace(0,15,10)  #used to create array with start,end and division steps

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [ ]:
np.logspace(1,40,5) #same like linspace, the division step is based on log

array([1.00000000e+01, 5.62341325e+10, 3.16227766e+20, 1.77827941e+30,
       1.00000000e+40])

In [ ]:
np.zeros(5) #array with all zers

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5) #array with all ones

array([1., 1., 1., 1., 1.])

random of numpy is used for normal distribution

In [ ]:
np.random.rand(0,3)

array([], shape=(0, 3), dtype=float64)

In [ ]:
np.random.randint(0,10)

1

Methods of Numpy

In [ ]:
arr = np.arange(0,11)

Statistics

In [ ]:
np.mean(arr)

5.0

In [ ]:
np.var(arr)

10.0

In [ ]:
np.median(arr)

5.0

In [ ]:
np.min(arr)

0

In [ ]:
np.max(arr)

10

In [ ]:
np.std(arr)

3.1622776601683795

In [ ]:
arr1 = np.arange(11,21)

Combining and splitting

In [ ]:
a= np.arange(0,11)
b= np.arange(11,21)
np.concatenate((a,b),axis=0) #combining

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])